Homework 1
VadimStolpovskiy/SPbU-F-Sharp pull request #1
Opened 2022-09-29 20:37 UTC by VadimStolpovskiy

0_0

2022-09-30 06:29 UTC, gsvgit requested changes
1. Файлы из папок obj и bin не должны попадать в репозиторий. Правильно приготовленный шаблон это обеспечивает. У Вас они попали. Вы что-то делаете не так.
2. Не надо называть вещи (файлы, папки, проекты, переменные) транслитом. Учите английский потихоньку и называйте нормально на английском.

2022-10-07 06:24 UTC, gsvgit requested changes

2022-10-07 06:24 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +namespace Homework.Tests
А это что такое?

2022-10-07 06:24 UTC, gsvgit commented on src/Homework/Task 1.fs
> +    let quickExp b n = b ** n
Точно?

2022-10-07 06:24 UTC, gsvgit commented on src/Homework/Task 1.fs
> +    let min x y =
Да ладно уже. Я на паре говорил, что ```min``` и ```max``` системные есть.

2022-10-07 06:24 UTC, gsvgit commented on src/Homework/Task 1.fs
> +        let mutable Min = arr[0]
А что, если массив пустой?
А почему стиль имён "поехал"?

2022-10-07 06:24 UTC, gsvgit commented on src/Homework/Task 1.fs
> +            |> Array.filter (fun elem -> elem % 2 = 1)
Отлично. А теперь давайте предположем, что модуль ```Array``` ещё не изобрели.

2022-10-07 06:24 UTC, gsvgit commented on src/Homework/Task 1.fs
> +        filter
И что-то не видно тестов для ревализованных функций.

2022-10-27 17:25 UTC, VadimStolpovskiy commented
Ураааа!!!

2022-10-30 07:39 UTC, gsvgit requested changes

2022-10-30 07:39 UTC, gsvgit commented on src/Homework/Library.fs
> +namespace Homework
Это тут откуда? Какое отношение имеет к домашке?

2022-10-30 07:39 UTC, gsvgit commented on src/Homework/Task1.fs
> +let exp (value: float) pow : float =
Точно ли только флоат может быть основанием?

2022-10-30 07:39 UTC, gsvgit commented on src/Homework/Task1.fs
> +        for i = 1 to pow do
А нельзя ли как-то эти циклы унифицировать?

2022-10-30 07:39 UTC, gsvgit commented on src/Homework/Task1.fs
> +    if pow = 1 then
Точно ли только флоат?

2022-10-30 07:39 UTC, gsvgit commented on src/Homework/Task1.fs
> +    if pow = 1 then
А зачем тут проверять значение показателя?

2022-10-30 07:39 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +    [<Tests>]
Опять же. Вы уже знаете про тестирование свойств. Тут есть, где их применить.

2022-10-30 17:03 UTC, VadimStolpovskiy commented on src/Homework/Task1.fs
> +let exp (value: float) pow : float =
Не совсем понял, Вы имеете в виду целые числа?

2022-10-30 17:07 UTC, gsvgit commented on src/Homework/Task1.fs
> +let exp (value: float) pow : float =
Я имею ввиду любые типи на которых определена операция умножения.

2022-11-04 13:11 UTC, gsvgit commented on src/Homework/Task1.fs
> +let diff (arr: int array) =
Правда ли, что разницу можно считать только между целыми числами?

2022-11-04 13:11 UTC, gsvgit commented on src/Homework/Task1.fs
> +let exp value pow =
Хорошо, Вы убрали аннотацию типов. Можете ли Вы теперь применить свою функцию к целым числам? А к байтам? А к числам с плавающей запятой? В тестах я что-то такого не наблюдаю. Проверьте, пожалуйста.

2022-11-04 13:11 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +            [ testProperty "Exponentiation | Naive and quick should return equal results"
Практически для всех функций нужны тесты с разными типами данных.

2022-11-11 05:13 UTC, VadimStolpovskiy commented on src/Homework/Task1.fs
> +let exp value pow =
Неполучаеца :D Как можно заставить функцию принимать все типы? Если я припишу inline, уберу из ее тела числа и заменю, например 1 на value / value, это будет сильно плохо?

2022-11-13 07:21 UTC, VadimStolpovskiy commented on src/Homework/Task1.fs
> +let exp value pow =
А с рекурсией это не работает. Подскажите пожалуйста 😢

2022-11-14 06:52 UTC, gsvgit commented on src/Homework/Task1.fs
> +let exp value pow =
Давайте постепенно. Почму не получается? В чём именно проблема?

2022-11-14 18:25 UTC, VadimStolpovskiy commented on src/Homework/Task1.fs
> +let exp value pow =
Ну если попытаться текущей версии функции передать аргумент другого типа (отличного от того, что компилятор сам обозначил), он ругается: 

`This expression was expected to have type ... but here has type ...`

Я хотел решить эту проблему с inline, но с рекурсией он не дружит, как я понял.

2022-11-15 07:26 UTC, gsvgit commented on src/Homework/Task1.fs
> +let exp value pow =
Вот что-то мне кажется, что проблемы возникают ещё до рекурсии и inline. Постарайтесь с этим разобраться. Хотя наблюдение про то, что inline не дружет с рекурсией правильное.

2022-11-26 06:41 UTC, gsvgit commented on src/Homework/Task1.fs
> +let diff (arr: float array) =
Правда ли, что минимум и максимум (ну и разница между ними) бывают только в массиве из  флоатов?

2022-11-26 06:41 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
А почему свойства только для интов? А какие-то ручные добавили для разных. Как-то это не очень логично.

2022-11-26 06:41 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +              testCase "Odds"
Мммм... А другие случаи? А может и свойства какие-то проверить можно?

2022-11-26 06:41 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +                  let actual = diff [| 43; -689; 3; 0; 573; 93 |]
О. Интересный вопрос. У Вас написано, что diff принимает массив флоатов, а тут Вы передаёте массив интов. Как это работает?

2022-11-26 08:32 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
Мы вроде бы условились, что показатель степени всегда целое число?

2022-11-26 08:34 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
Это да. А какого типа здесь основание?

2022-11-26 09:03 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
Идеешка показывает, что int, извиняюсь... Я думал, будут использоваться различные типы. Тогда лучше добавить для каждого отдельные тесты?

2022-11-26 09:05 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
Ну да. Не для каждого, конечно. Все перебирать упаритесь. Но ещё для нескольких разных, для которых понятно, что такое возведение в степень.

2022-11-26 09:26 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
А можно ограничить количество знаков после запятой? А то там какие-то страшные вещи происходят.

2022-11-26 09:50 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
Не надо так делать. Надо разобраться, что за вещи происходят. Ну и понять, как с ними жить дальше.

2022-11-26 12:49 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
При входных данных типа таких: ```1.885059231 4```
У разных функций получается:
```
12,626994851889098
12,626994851889096
``` 
При их сравнении конечно ```False```
Я скорее про это, можно ли корректно сравнивать нечто подобное? Или, что-то мне подсказывает, в таком случае лучше не сравнивать вовсе?

2022-11-28 08:06 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
Хм. А почему такое происходит? Какой ответ правильный?

2022-11-28 13:54 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
Какая-то погрешность при операциях над числами с плавающей запятой, точно откуда берется непонятно. Если сравнивать с оператором **, то наивная правильная.

2022-11-28 16:05 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
Это работает очень странно, иногда даже быстрая совпадает, а наивная - нет. Разница между ними начинает быть больше 1 где-то на 50 степени. Если округлять ее и сравнивать с нулем, тесты проходят.

Но теперь падает на 1.8*10^308 в квадрате, выводит вопросительный знак... Или тестировать с вещественными числами изначально плохая идея? Такое ощущение, что это ограничивание входных данных и добавление новых условий никогда не кончится.

2022-11-29 05:27 UTC, gsvgit commented on tests/Homework.Tests/Tests.fs
> +                  if x <> 0 && y <> 0 then
Ну, Вы правы в том, что накапливается некоторая погрешность. Так что флоаты надо аккуртано сравнивать. И в fsCheck для этого есть определённые механизмы. Про них Иван, например, знает. Можете у него спросить. Ну или начать с того, чтобы самостоятельно в документации выяснить.

2022-11-30 06:45 UTC, gsvgit requested changes

2022-11-30 06:45 UTC, gsvgit commented on tests/Homework.Tests/Task1Tests.fs
> +                      true
Не уверен, что понял. Функции возведения в степень у Вас умеют обрабатывать отрицательные показатели. Зачем Вы их тут фильтруете?

2022-11-30 06:45 UTC, gsvgit commented on tests/Homework.Tests/Task1Tests.fs
> +                      (x = 0 && y <= 0)
Очень странная фильтарция. Всё, что Вы отфильтровываете --- корректные входные значения.

2022-11-30 06:45 UTC, gsvgit commented on tests/Homework.Tests/Task1Tests.fs
> +                  let actual = diff [| 43; -689; 3; 0; 573; 93 |]
Есть `Array.min` и `Array.max`. Кажется, на этом можно свойство потестировать.

2022-11-30 06:45 UTC, gsvgit commented on tests/Homework.Tests/Task1Tests.fs
> +              <| fun _ ->
Думаю, Вы можете быстро посчитать количество нечётных между двумя значениями. Тоже хорошая идея для проверки свойств.

2022-11-30 09:10 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task1Tests.fs
> +                      true
Теперь когда функция дженериковая, с интами и подобными им типами происходит целочисленное деление.

2022-11-30 09:15 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task1Tests.fs
> +                      (x = 0 && y <= 0)
Может где-то ошибся, я хотел отфильтровать 0 в степени меньше или равно 0.

2022-11-30 19:37 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task1Tests.fs
> +                      (x = 0 && y <= 0)
С Infinity понимаю, но почему NaN корректно? А границы просто, чтобы не получались запредельные значения и всякие вопросительные знаки. Это же не так критично?

2022-12-01 06:26 UTC, gsvgit commented on tests/Homework.Tests/Task1Tests.fs
> +                      (x = 0 && y <= 0)
1. NaN --- это корректное значение для типа float. Ваша функция работатет с этьим типом, значит должна обрабатывать все его допустимые значения.
2. Критично. Опять же, ровно потому, что если Ваша функция работает с типом float, то должна обрабатывать любые допустимые для этого типа значения.

2022-12-04 07:50 UTC, gsvgit commented on src/Homework/Task1.fs
> +let inline diff (arr: ^a array) =
А зачем тут знак `^` перед типом `a` ?

2022-12-04 07:50 UTC, gsvgit commented on tests/Homework.Tests/Task1Tests.fs
> +                      true
Всё ещё не понял. Можно в итоге возводить в целую отрицательную степерь или нет? Функции возведения написаныы так, будто можно.

2022-12-04 07:50 UTC, gsvgit commented on tests/Homework.Tests/Task1Tests.fs
> +                      Expect.isTrue true
Что?

2022-12-04 07:50 UTC, gsvgit commented on tests/Homework.Tests/Task1Tests.fs
> +                          Expect.isTrue true
Зачем так?

2022-12-04 07:50 UTC, gsvgit commented on tests/Homework.Tests/Task1Tests.fs
> +                  if m < 0 || n < 0 then
И всё же, что не так с отрицательными показателями?

2022-12-04 08:28 UTC, VadimStolpovskiy commented on src/Homework/Task1.fs
> +let inline diff (arr: ^a array) =
Универсальный тип

2022-12-04 08:32 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task1Tests.fs
> +                  if m < 0 || n < 0 then
При делении GenericOne на целое число получается 0. Я не знаю, что с этим делать...

2022-12-04 08:33 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task1Tests.fs
> +                          Expect.isTrue true
Expect.floatClose не работает с NaN и infinity, насколько я понял, даже NaN = NaN будет false. Поэтому они проверяются отдельно.

2022-12-04 08:34 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task1Tests.fs
> +                      Expect.isTrue true
Я хотел отфильтровать 0 в степени меньше или равно 0.

2022-12-04 09:32 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task1Tests.fs
> +                      Expect.isTrue true
Все, я понял.

2022-12-05 13:48 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task1Tests.fs
> +                      true
Функцию можно переписать 😁

2022-12-06 16:12 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task1Tests.fs
> +                  if m < 0 || n < 0 then
Семен Вячеславович, помогите пожалуйста, что я могу сделать?

2022-12-10 17:43 UTC, gsvgit approved these changes

2022-12-10 21:23 UTC, merged