Homework 2
VadimStolpovskiy/SPbU-F-Sharp pull request #3
Opened 2022-12-17 05:53 UTC by VadimStolpovskiy

First commit

2022-12-19 06:10 UTC, gsvgit requested changes

2022-12-19 06:10 UTC, gsvgit commented on src/Homework/ConsList.fs
> +let rec partition lst pivot =
Можно ли сделать partition который по произвольному предикату разбивает?

2022-12-19 06:10 UTC, gsvgit commented on src/Homework/OOPList.fs
> +    | :? NonEmptyList<'value> as lst -> lst.Head
А если список оказался пустым?

2022-12-19 06:10 UTC, gsvgit commented on src/Homework/OOPList.fs
> +    | :? EmptyList<'value> -> EmptyList() :> OOPList<'value>
А как у Вас так получилось у пустого списка взять хвост?

2022-12-19 06:10 UTC, gsvgit commented on src/Homework/OOPList.fs
> +    | :? NonEmptyList<'value> as lst -> [ lst.Head ] @ OOPListToList lst.Tail
И тут тоже что-то странное.

2022-12-19 06:10 UTC, gsvgit commented on src/Homework/OOPList.fs
> +let rec partition (lst: OOPList<'value>) pivot =
Аналогичный вопрос про предикат.

2022-12-19 06:10 UTC, gsvgit commented on tests/Homework.Tests/Task1Tests.fs
> +    //[<Tests>]
А зачем эти тесты выключили?

2022-12-19 06:10 UTC, gsvgit commented on tests/Homework.Tests/Task2Tests.fs
> +              testProperty "Bubble sort ConsList<string> | Comparison with system sort"
А бывают какие-нибудь ещё типы, которые можно сортировать?

2022-12-19 06:10 UTC, gsvgit commented on tests/Homework.Tests/Task2Tests.fs
> +              testProperty "Concat OOPList<int> | Comparison with system concat"
А поведение конкатенации как-то зависит от типа содержимого?

2022-12-19 06:41 UTC, VadimStolpovskiy commented on src/Homework/ConsList.fs
> +    | Cons(hd, tl) -> [ hd ] @ consListToList tl
@ — оператор конкатенации двух листов. А что именно странное?

2022-12-19 06:50 UTC, gsvgit commented on src/Homework/ConsList.fs
> +    | Cons(hd, tl) -> [ hd ] @ consListToList tl
Зачем создавать список из одного элемента?

2022-12-19 06:52 UTC, VadimStolpovskiy commented on src/Homework/ConsList.fs
> +let rec partition lst pivot =
Не уверен, что понял. А сейчас какой?

2022-12-19 06:56 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task1Tests.fs
> +    //[<Tests>]
Чтобы не запускались лишний раз, забыл вернуть.

2022-12-19 07:02 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task2Tests.fs
> +              testProperty "Concat OOPList<int> | Comparison with system concat"
Не должно. А что?

2022-12-19 07:08 UTC, gsvgit commented on tests/Homework.Tests/Task2Tests.fs
> +              testProperty "Concat OOPList<int> | Comparison with system concat"
А в чём тогда великий смысл таких тестов?

2022-12-19 07:08 UTC, gsvgit commented on src/Homework/ConsList.fs
> +let rec partition lst pivot =
Что такое предикат?

2022-12-19 07:11 UTC, VadimStolpovskiy commented on src/Homework/ConsList.fs
> +    | Cons(hd, tl) -> [ hd ] @ consListToList tl
Да, наверное это затратно.

2022-12-19 07:13 UTC, VadimStolpovskiy commented on tests/Homework.Tests/Task2Tests.fs
> +              testProperty "Concat OOPList<int> | Comparison with system concat"
Где явно типы обозначены? Ну чтобы проверить, что работает с разными типами, как в прошлой домашке.

2022-12-19 07:58 UTC, gsvgit commented on tests/Homework.Tests/Task2Tests.fs
> +              testProperty "Concat OOPList<int> | Comparison with system concat"
Так если поведение не зависит от типа, то зачем? Раньше хоть были какие-то принципиальные проблемы.

2022-12-19 09:24 UTC, VadimStolpovskiy commented on src/Homework/ConsList.fs
> +let rec partition lst pivot =
Какое-то условие. Кажется, понял. Функция принимает предикат и по нему распределяет предметы в первый либо второй список?

2022-12-19 09:38 UTC, gsvgit commented on src/Homework/ConsList.fs
> +let rec partition lst pivot =
Да.

2022-12-20 12:38 UTC, VadimStolpovskiy commented
С предикатами как-то не задалось...

2022-12-21 13:10 UTC, gsvgit commented
> С предикатами как-то не задалось...

Разберитесь всё таки с предикатами.

2022-12-22 06:58 UTC, gsvgit commented on src/Homework/ConsList.fs
> +            Cons(hd, fst parts), snd parts
А можно ли сделать так, чтобы не надо бвло использовать fst и  snd?

2022-12-22 06:58 UTC, gsvgit commented on src/Homework/OOPList.fs
> +let rec partition predicate (lst: OOPList<'value>) =
А если предположить, что у нас таки нет честных функций?

2022-12-22 06:58 UTC, gsvgit commented on src/Homework/Task2.fs
> +            let parts = ConsList.partition (fun elem -> elem < hd) tl
Можно ли предикат короче записать? Без введения анонимной функции.

2022-12-22 07:48 UTC, VadimStolpovskiy commented on src/Homework/ConsList.fs
> +            Cons(hd, fst parts), snd parts
Сделать два пустых списка и в них добавлять элементы?

2022-12-22 07:48 UTC, VadimStolpovskiy commented on src/Homework/OOPList.fs
> +let rec partition predicate (lst: OOPList<'value>) =
Не совсем понял, что это значит.

2022-12-22 07:49 UTC, VadimStolpovskiy commented on src/Homework/Task2.fs
> +            let parts = ConsList.partition (fun elem -> elem < hd) tl
Наверное можно, но мне не представляется как.

2022-12-22 09:46 UTC, gsvgit commented on src/Homework/Task2.fs
> +            let parts = ConsList.partition (fun elem -> elem < hd) tl
Попробуйте вспомнить, что `<` --- это тоже просто функция.

2022-12-22 09:46 UTC, gsvgit commented on src/Homework/OOPList.fs
> +let rec partition predicate (lst: OOPList<'value>) =
Это значит, что Вы не можете передать `predicate` просто как функцию.

2022-12-22 09:46 UTC, gsvgit commented on src/Homework/ConsList.fs
> +            Cons(hd, fst parts), snd parts
Не. Гораздо проще.

2022-12-24 15:30 UTC, VadimStolpovskiy commented on src/Homework/Task2.fs
> +            let parts = ConsList.partition (fun elem -> elem < hd) tl
Ее можно как-то переопределить для себя? Как с плюсом или умножением было. (<)

2022-12-24 16:18 UTC, gsvgit commented on src/Homework/Task2.fs
> +            let parts = ConsList.partition (fun elem -> elem < hd) tl
Не надо переопределять

2022-12-26 12:48 UTC, VadimStolpovskiy commented on src/Homework/Task2.fs
> +            let parts = ConsList.partition (fun elem -> elem < hd) tl
Никак не могу понять, что поставить на место `(_ < hd)`. Или я не в том направлении думаю?

2022-12-27 08:30 UTC, gsvgit commented on src/Homework/Task2.fs
> +            let parts = ConsList.partition (fun elem -> elem < hd) tl
Просто попробуйте избавиться от анонимной лямбды (через частичное применение, видимо).

2022-12-28 07:16 UTC, gsvgit approved these changes

2022-12-28 07:16 UTC, gsvgit commented on src/Homework/Task2.fs
> +            let headIsMoreThan = (>) hd
Ну да. Как-то так. Правда не очень понятно, зачем это выделять и делать отдельное связывание.

2022-12-28 13:43 UTC, merged