Homework 3
VadimStolpovskiy/SPbU-F-Sharp pull request #4
Opened 2022-12-28 19:20 UTC by VadimStolpovskiy

1.  Описать алгебраический тип, задающий дерево, в котором внутренний узел может иметь произвольное количество сыновей. Листья и внутренние узлы хранят некоторые значени произвольного типа.

2. Реализовать функцию, которая по дереву,  находит количество различных элементов, хранящихся в узлах.

3. Реализовать функцию, которая по дереву,  строит список, содержащий все значения из всех узлов. Для списка использовать тип ConsList.

2022-12-29 06:42 UTC, gsvgit requested changes
Где-то  я уже видел чертовски похожее решение. Давайте для профилактики Вы модифицируете третью функцию так, чтобы значения в списке лежали в следующем порядке: сперва значения из всех поддеревьев справа налево, потом значение из корня. То есть если у меня есть дерево `Node (1, [Leaf 2; Leaf 3])`, то результат --- `[3; 2; 1]`.

2022-12-29 07:15 UTC, VadimStolpovskiy commented
> Сперва значения из всех поддеревьев справа налево, потом значение из корня. То есть если у меня есть дерево `Node (1, [Leaf 2; Leaf 3])`, то результат --- `[3; 2; 1]`.

Может быть я неправильно понял, но сейчас функция и работает таким образом?

2022-12-30 09:44 UTC, gsvgit commented
> > Сперва значения из всех поддеревьев справа налево, потом значение из корня. То есть если у меня есть дерево `Node (1, [Leaf 2; Leaf 3])`, то результат --- `[3; 2; 1]`.
> 
> Может быть я неправильно понял, но сейчас функция и работает таким образом?

Допустим. Тогда пусть будет просто две версии: одна работает, как выше, а вторая наоборот: сперва корень, потом сыновья слева направо.

2023-01-01 18:41 UTC, VadimStolpovskiy commented
С Новым годом! 😁

2023-01-02 07:28 UTC, gsvgit reviewed
И Вас с наступившим)

2023-01-02 07:28 UTC, gsvgit commented on src/Homework/Tree.fs
> +let rec fold folder acc tree =
Ничего не понял. Вижу всё ещё один fold, которые ничего не знает про то, что порядок бывает разным.

2023-01-02 11:42 UTC, VadimStolpovskiy commented on src/Homework/Tree.fs
> +let rec fold folder acc tree =
Я теперь тоже ничего не понлял, если честно... Надо же было реализовать вторую версию функции которая строит список по дереву (toConsList)?

2023-01-02 14:36 UTC, gsvgit commented on src/Homework/Tree.fs
> +let rec fold folder acc tree =
Не. Надо два fold-а на дереве, которые в разном порядке его элементы собирают.

2023-02-15 06:43 UTC, gsvgit commented on src/Homework/ConsList.fs
> +    match lst with
А почему в прямом фолде есть магическая f, а тут нету? А как надо?

2023-02-15 06:43 UTC, gsvgit commented on src/Homework/Tree.fs
> +
И тут тоже. Таки нужна эта f или нет?

2023-02-15 06:43 UTC, gsvgit commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
А можн ли найти такой тип, чтобы не надо было вот этот код писать?

2023-02-15 11:46 UTC, VadimStolpovskiy commented on src/Homework/Tree.fs
> +
Думаю, не нужна 😁

2023-02-15 11:52 UTC, VadimStolpovskiy commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
Seq?

2023-02-15 12:37 UTC, gsvgit commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
Проблема в том, что это не множество

2023-02-16 06:46 UTC, VadimStolpovskiy commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
Кажется, только Set и Map представляют собой множества. Насколько я понял, основное между ними отличие в том, что Map связывает элементы с ключами, и по ним осуществляется доступ. В моем представлении реализация такая ("Set" --- какой-то тип множества):
```
let countDistinct tree =
    let result = fold Set.add Set.empty tree
    result.Count
```
Но Set.add по идее должен возвращать набор элементов типа 'a, а folder-функция должна возвращать просто элемент типа 'a.

2023-02-18 07:23 UTC, VadimStolpovskiy commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
Караул

2023-02-20 05:55 UTC, gsvgit commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
Я про другое. Есть много способов реализовать множество. Соотвтетсвенно, есть разные типы.

2023-04-08 10:30 UTC, VadimStolpovskiy commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
Прошу прощения за продолжительное отсутствие... Я все-таки не до конца понял и хотел бы прояснить, Вы предлагаете реализовать какой-то свой тип множества или использовать существующий в расположении F#? И в обоих случаях непонятно, как и где такое можно найти, узнать подробнее об этом.

2023-04-08 10:55 UTC, gsvgit commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-fsharpset-1.html

2023-04-08 12:38 UTC, VadimStolpovskiy commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
После изучения страницы хочется написать `let result = fold (+) Set.empty tree`, но опять те же грабли. Такое ощущение, будто чего-то самую малость не хватает. Или же под "не писать этот код" Вы имели в виду использование fold'а? Может стоит подумать над чем-то другим?

2023-04-09 05:16 UTC, gsvgit commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
"Те же" --- это какие?

2023-04-09 06:14 UTC, VadimStolpovskiy commented on src/Homework/Tree.fs
> +    let add (set: HashSet<'value>) value =
Выше я приводил код, в котором типы не соответствовали, тут нечто подобное.

2023-04-10 07:59 UTC, gsvgit approved these changes

2023-04-10 08:11 UTC, merged